@baseUrl = http://localhost:3001
@jwtToken = {{AuthLogin.response.body.accessToken}}

@postUuid = {{createPost.response.body.id}}
@postSlug = {{createPost.response.body.slug}}

@imagePath = {{uploadImage.response.body.url}}
@imageUrl = {{baseUrl}}{{imagePath}}

@userNameForTesting = Luiz
@userEmailForTesting = luiz@email.com
@userPasswordForTesting = 123456
@userNewPasswordForTesting = 123456

###############################################################################
# AUTH ########################################################################
###############################################################################

## create user
# @name CreateUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "carlos",
  "email": "carlos@gmail.com",
  "password": "123456"
}

###

## auth login
# @name AuthLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "carlosnew@gmail.com",
  "password": "123456"
}

###

## update (patch) user
# @name UpdateUser
PATCH {{baseUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "carlos new",
  "email": "carlosnew@gmail.com"
}

###

## update (patch) user password
# @name UpdateUserPassword
PATCH {{baseUrl}}/users/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "currentPassword": "123456",
  "newPassword": "123456"
}

###

## get users
# @name GetUsers
GET {{baseUrl}}/users
Authorization: Bearer {{jwtToken}}

###

## get user by id
# @name GetUserById
GET {{baseUrl}}/users/11fcb5b8-a42c-4abd-b40c-2d21da295c53
Authorization: Bearer {{jwtToken}}

###

## get me
# @name GetMe
GET {{baseUrl}}/users/me
Authorization: Bearer {{jwtToken}}

###

## delete me
# @name DeleteMe
PATCH {{baseUrl}}/users/me/soft-delete
Authorization: Bearer {{jwtToken}}

###############################################################################
# POST ########################################################################
###############################################################################

## create post
# @name createPost
POST {{baseUrl}}/posts
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title": "Título do post - carlos novo 11/08",
  "summary": "Um resumo sobre o post",
  "content": "Conteúdo muito bacana e legal sobre o post olha q manero haha"
}

###

## get all public posts
# @name getAllPublic
GET {{baseUrl}}/posts

###

## get all my posts
# @name getAllMyPosts
GET {{baseUrl}}/posts/me
Authorization: Bearer {{jwtToken}}
###

## get post by id
# @name getPostById
GET {{baseUrl}}/posts/id/{{postUuid}}
Authorization: Bearer {{jwtToken}}

###
## get post by slug
# @name getPostBySlug
GET {{baseUrl}}/posts/slug/{{postSlug}}
###

## update post
# @name updatePost
PATCH {{baseUrl}}/posts/{{postUuid}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title": "NOVO - Título do post 11/08/2025",
  "excerpt": "NOVO - Excerto",
  "content": "NOVO - Conteúdo",
  "published": false
}

###

## soft delete post
# @name softDeletePost
PATCH {{baseUrl}}/posts/soft-delete/{{postUuid}}
Authorization: Bearer {{jwtToken}}

###############################################################################
# UPLOAD ######################################################################
###############################################################################

## upload image
# @name uploadImage
POST {{baseUrl}}/upload
Authorization: Bearer {{jwtToken}}
Content-Type: multipart/form-data; boundary=----BryenFormBoundary

------BryenFormBoundary
Content-Disposition: form-data; name="file"; filename="exemplo.png"
Content-Type: image/png

< ../dev/images/image.jpeg
------BryenFormBoundary--

###

## read image
# @name readImage
GET {{imageUrl}}

###############################################################################
