@baseUrl = http://localhost:3001
@jwtToken = {{AuthLogin.response.body.accessToken}}

@postUuid = {{createPostOwned.response.body.id}}
@postSlug = {{createPostOwned.response.body.slug}}

@imagePath = {{uploadImage.response.body.url}}
@imageUrl = {{baseUrl}}{{imagePath}}

@userNameForTesting = Luiz
@userEmailForTesting = luiz@email.com
@userPasswordForTesting = 123456
@userNewPasswordForTesting = 123456

###############################################################################
# AUTH ########################################################################
###############################################################################

## create user
# @name CreateUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "rudney",
  "email": "rudney@gmail.com",
  "password": "123456"
}

###

## auth login
# @name AuthLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "rudney@gmail.com",
  "password": "123456"
}

###

## update (patch) user
# @name UpdateUser
PATCH {{baseUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "rudney new",
  "email": "rudneynew@gmail.com"
}

###

## update (patch) user password
# @name UpdateUserPassword
PATCH {{baseUrl}}/users/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "currentPassword": "123456",
  "newPassword": "123456"
}

###

## get users
# @name GetUsers
GET {{baseUrl}}/users
Authorization: Bearer {{jwtToken}}

###

## get user by id
# @name GetUserById
GET {{baseUrl}}/users/11fcb5b8-a42c-4abd-b40c-2d21da295c53
Authorization: Bearer {{jwtToken}}

###

## get me
# @name GetMe
GET {{baseUrl}}/users/me
Authorization: Bearer {{jwtToken}}

###

## delete me
# @name DeleteMe
PATCH {{baseUrl}}/users/me/soft-delete
Authorization: Bearer {{jwtToken}}

###############################################################################
# POST ########################################################################
###############################################################################

## create post
# @name createPost
POST {{baseUrl}}/post
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title": "Título do post 2",
  "summary": "Um resumo sobre o post",
  "content": "Conteúdo muito bacana e legal sobre o post olha q manero haha"
}

###

## read all post public
# @name readAllPostPublic
GET {{baseUrl}}/post/

###

## read one post public
# @name readOnePostPublic
GET {{baseUrl}}/post/{{postSlug}}

###

## read all post owned
# @name readAllPostOwned
GET {{baseUrl}}/post/me
Authorization: Bearer {{jwtToken}}

###

## read one post owned
# @name readOnePostOwned
GET {{baseUrl}}/post/me/{{postUuid}}
Authorization: Bearer {{jwtToken}}

###

## update one post owned
# @name updateOnePostOwned
PATCH {{baseUrl}}/post/me/{{postUuid}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title": "NOVO - Título do post",
  "excerpt": "NOVO - Excerto",
  "content": "NOVO - Conteúdo",
  "published": true
}

###

## delete one post owned
# @name deleteOnePostOwned
DELETE {{baseUrl}}/post/me/{{postUuid}}
Authorization: Bearer {{jwtToken}}

###############################################################################
# UPLOAD ######################################################################
###############################################################################

## upload image
# @name uploadImage
POST {{baseUrl}}/upload
Authorization: Bearer {{jwtToken}}
Content-Type: multipart/form-data; boundary=----BryenFormBoundary

------BryenFormBoundary
Content-Disposition: form-data; name="file"; filename="exemplo.png"
Content-Type: image/png

< ../dev/images/sample-image.jpeg
------BryenFormBoundary--

###

## read image
# @name readImage
GET {{imageUrl}}

###############################################################################
