@baseUrl = http://localhost:3001
@jwtToken = {{AuthLogin.response.body.accessToken}}


## create user
# @name CreateUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "rudney",
  "email": "rudney@gmail.com",
  "password": "123456"
}

###

## auth login
# @name AuthLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "rudney@gmail.com",
  "password": "123456"
}


###

## update (patch) user
# @name UpdateUser

PATCH {{baseUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "rudney new",
  "email": "rudneynew@gmail.com"
}

###

## update (patch) user
# @name UpdateUser

PATCH {{baseUrl}}/users/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "currentPassword": "123456",
  "newPassword": "123456"
}

###

## get users
# @name GetUsers

GET {{baseUrl}}/users
Authorization: Bearer {{jwtToken}}

###

## get user by id
# @name GetUsers

GET {{baseUrl}}/users/11fcb5b8-a42c-4abd-b40c-2d21da295c53
Authorization: Bearer {{jwtToken}}


###

## get me
# @name GetMe

GET {{baseUrl}}/users/me
Authorization: Bearer {{jwtToken}}


###

## Delete me
# @name DeleteMe

PATCH {{baseUrl}}/users/me/soft-delete
Authorization: Bearer {{jwtToken}}